version: "3.9"

services:
  db:
    image: postgres:15
    container_name: synergy-db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  odoo:
    image: odoo:18
    container_name: synergy-odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons   # Your custom SynergySphere module
      - ./config:/etc/odoo

  nginx:
    image: nginx:latest
    container_name: synergy-nginx
    depends_on:
      - odoo
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

volumes:
  db_data:
  odoo-web-data:
